name: Publish Specific Commit

on:
  workflow_dispatch:
    inputs:
      sha:
        description: 'The commit SHA to checkout and publish'
        required: true

jobs:
  build_commit:
    runs-on: [self-hosted, linux]
    env:
      TARGET_BRANCH: ${{ github.event.inputs.branch }}
      COMMIT_SHA: ${{ github.event.inputs.sha }}
      
    steps:
      - name: Determine Commit SHA
        id: determine_sha
        run: |
          if [ -z "${{ github.event.inputs.sha }}" ]; then
            echo "COMMIT_SHA=${{ github.sha }}" >> $GITHUB_ENV
          else
            echo "COMMIT_SHA=${{ github.event.inputs.sha }}" >> $GITHUB_ENV
          fi
            
      - name: Checkout the repository at SHA
        uses: actions/checkout@v3
        with:
          ref: ${{ env.COMMIT_SHA }}

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build With Gradle
        run: ./gradlew build

      - name: Test With Gradle
        run: ./gradlew test

      - name: Publish Build
        run: |
          echo "Publishing build..."
          ./gradlew publish -PmavenRepoUrl=${{ secrets.MAVEN_REPO }}
