name: Publish Specific Commit

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to check out '
        required: true
        default: ${{ github.event.repository.default_branch }}
      sha:
        description: 'The commit SHA to checkout and publish'
        required: true

jobs:
  build_commit:
    runs-on: [self-hosted, linux]
    env:
      TARGET_BRANCH: ${{ github.event.inputs.branch }}
      COMMIT_SHA: ${{ github.event.inputs.sha }}

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          ref: ${{ env.COMMIT_SHA }}
          fetch-depth: 0
          repository: ${{ github.repository }}

      - name: Ensure correct branch
        run: |
          git fetch origin ${{ env.TARGET_BRANCH }}
          git checkout ${{ env.TARGET_BRANCH }}
          git reset --hard ${{ env.COMMIT_SHA }}

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 8

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build With Gradle
        run: ./gradlew build

      - name: Test With Gradle
        run: ./gradlew test

      - name: Publish Build
        run: |
          echo "Publishing build..."
          ./gradlew publish -PmavenRepoUrl=${{ secrets.MAVEN_REPO }}
