name: Publish Specific Commit

on:
  workflow_dispatch:
    inputs:
      sha:
        description: 'The commit SHA to checkout and publish'
        required: true

jobs:
  build_commit:
    runs-on: [self-hosted, linux]
    env:
      TARGET_BRANCH: ${{ github.event.inputs.branch }}
      COMMIT_SHA: ${{ github.event.inputs.sha }}

    steps:
      - name: Determine Commit SHA
        id: determine_sha
        run: |
          if [ -z "${{ github.event.inputs.sha }}" ]; then
            echo "commit_sha=${GITHUB_SHA}" >> $GITHUB_OUTPUT
          else
            echo "commit_sha=${{ github.event.inputs.sha }}" >> $GITHUB_OUTPUT
            
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.determine_sha.outputs.commit_sha }}

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 8

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build With Gradle
        run: ./gradlew build

      - name: Test With Gradle
        run: ./gradlew test

      - name: Publish Build
        run: |
          echo "Publishing build..."
          ./gradlew publish -PmavenRepoUrl=${{ secrets.MAVEN_REPO }}
